name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@master
    - name: Run a one-line script
      run: |
        cd build
        ./compile.sh BOARD="odroidxu4" BRANCH="current" RELEASE="buster" CARD_DEVICE="/dev/sda" KERNEL_ONLY="no" KERNEL_CONFIGURE="no" INSTALL_HEADERS="yes" BUILD_DESKTOP="no" BUILD_MINIMAL="yes"
